from __future__ import annotations

import hashlib
import json
import re
import urllib.error
import urllib.parse
import urllib.request
from datetime import timedelta, timezone as datetime_timezone
from typing import Any

from django.conf import settings
from django.utils import timezone

from leads.models import LeadEventOutbox, LeadSubmission
from marketing.models import MarketingIntegration


DATA_MANAGER_SCOPE = 'https://www.googleapis.com/auth/datamanager'
DATA_MANAGER_INGEST_URL = 'https://datamanager.googleapis.com/v1/events:ingest'
DATA_MANAGER_STATUS_URL = 'https://datamanager.googleapis.com/v1/requestStatus:retrieve'


class GoogleDataManagerError(ValueError):
    pass


def _hex_sha256(value: str) -> str:
    return hashlib.sha256(value.encode('utf-8')).hexdigest().upper()


def normalize_google_email(value: str) -> str:
    normalized = ''.join(str(value or '').split()).lower()
    if '@' not in normalized:
        return normalized
    local_part, domain = normalized.rsplit('@', 1)
    if domain in {'gmail.com', 'googlemail.com'}:
        local_part = local_part.split('+', 1)[0].replace('.', '')
    return f'{local_part}@{domain}'


def normalize_google_phone(value: str) -> str:
    raw = str(value or '').strip()
    if raw.startswith('+'):
        digits = re.sub(r'\D', '', raw)
    elif raw.startswith('00'):
        digits = re.sub(r'\D', '', raw)[2:]
    else:
        return ''
    if not 8 <= len(digits) <= 15 or digits.startswith('0'):
        return ''
    return f'+{digits}'


def google_event_time(submission: LeadSubmission, stage_key: str):
    timestamps = {
        'qualified': submission.qualified_at,
        'won': submission.won_at,
    }
    return timestamps.get(stage_key) or submission.stage_updated_at or submission.submitted_at


def _rfc3339(value) -> str:
    aware = value or timezone.now()
    if timezone.is_naive(aware):
        aware = timezone.make_aware(aware, timezone.get_current_timezone())
    return aware.astimezone(datetime_timezone.utc).isoformat().replace('+00:00', 'Z')


def _google_event_source(submission: LeadSubmission) -> str:
    # Qualified and won events are generated by the CRM stage decision. The
    # original acquisition channel does not describe where this later event
    # happened, so it must not be reused as Google's EventSource.
    return 'OTHER'


def _request_status_payloads(response: dict[str, Any] | None) -> list[dict[str, Any]]:
    payload = response if isinstance(response, dict) else {}
    candidates = [payload]
    nested = payload.get('request_status')
    if isinstance(nested, dict) and nested is not payload:
        candidates.append(nested)
    return candidates


def google_response_warnings(response: dict[str, Any] | None) -> list[str]:
    messages: list[str] = []
    for status_payload in _request_status_payloads(response):
        for warning in status_payload.get('fieldWarnings') or []:
            if not isinstance(warning, dict):
                continue
            field = str(warning.get('field') or '').strip()
            detail = str(warning.get('description') or warning.get('reason') or '').strip()
            message = ': '.join(part for part in (field, detail) if part)
            if message:
                messages.append(message)
        for status in status_payload.get('requestStatusPerDestination') or []:
            if not isinstance(status, dict):
                continue
            warning_info = status.get('warningInfo') or {}
            if not isinstance(warning_info, dict):
                continue
            for warning_count in warning_info.get('warningCounts') or []:
                if not isinstance(warning_count, dict):
                    continue
                reason = str(warning_count.get('reason') or '').strip()
                count = str(
                    warning_count.get('recordCount')
                    if warning_count.get('recordCount') not in (None, '')
                    else warning_count.get('count') or ''
                ).strip()
                message = ' x '.join(part for part in (reason, count) if part)
                if message:
                    messages.append(message)
    return list(dict.fromkeys(messages))


def google_response_errors(response: dict[str, Any] | None) -> list[str]:
    messages: list[str] = []
    for status_payload in _request_status_payloads(response):
        for status in status_payload.get('requestStatusPerDestination') or []:
            if not isinstance(status, dict):
                continue
            error_info = status.get('errorInfo') or {}
            if not isinstance(error_info, dict):
                continue
            for error_count in error_info.get('errorCounts') or []:
                if not isinstance(error_count, dict):
                    continue
                reason = str(error_count.get('reason') or '').strip()
                count = str(
                    error_count.get('recordCount')
                    if error_count.get('recordCount') not in (None, '')
                    else error_count.get('count') or ''
                ).strip()
                message = ' x '.join(part for part in (reason, count) if part)
                if message:
                    messages.append(message)
    return list(dict.fromkeys(messages))


def _conversion_action_id(integration: MarketingIntegration, stage_key: str) -> str:
    config = dict(integration.config_json or {})
    key = 'qualified_conversion_action_id' if stage_key == 'qualified' else 'converted_conversion_action_id'
    value = str(config.get(key) or '').strip()
    if not value:
        raise GoogleDataManagerError(f'Google Data Manager 缺少 {key}。')
    return value


def build_google_data_manager_payload(
    submission: LeadSubmission,
    integration: MarketingIntegration,
    *,
    stage_key: str,
) -> dict[str, Any]:
    if stage_key not in {'qualified', 'won'}:
        raise GoogleDataManagerError('Google Data Manager 只接收 Qualified/Converted Lead。')
    if not bool((getattr(submission, 'consent_json', {}) or {}).get('marketing')):
        raise GoogleDataManagerError('线索未授权广告测量，不得发送 Google Data Manager。')
    account_id = re.sub(r'\D', '', str(integration.public_id or ''))
    if not account_id:
        raise GoogleDataManagerError('Google Ads customer ID 未配置。')
    config = dict(integration.config_json or {})
    destination: dict[str, Any] = {
        'reference': f'{stage_key}-lead',
        'operatingAccount': {'accountId': account_id, 'accountType': 'GOOGLE_ADS'},
        'productDestinationId': _conversion_action_id(integration, stage_key),
    }
    login_account_id = re.sub(r'\D', '', str(config.get('login_account_id') or ''))
    if login_account_id and login_account_id != account_id:
        destination['loginAccount'] = {'accountId': login_account_id, 'accountType': 'GOOGLE_ADS'}

    identifiers: list[dict[str, str]] = []
    email = normalize_google_email(submission.email)
    phone = normalize_google_phone(submission.phone)
    if email:
        identifiers.append({'emailAddress': _hex_sha256(email)})
    if phone:
        identifiers.append({'phoneNumber': _hex_sha256(phone)})

    stored_ids = dict(submission.identifiers_json or {})
    ad_identifiers = {
        key: str(stored_ids.get(key) or '').strip()
        for key in ('gclid', 'gbraid', 'wbraid')
        if str(stored_ids.get(key) or '').strip()
    }
    session_attributes = str(stored_ids.get('google_session_attributes') or '').strip()
    if session_attributes:
        ad_identifiers['sessionAttributes'] = session_attributes
    timestamp = google_event_time(submission, stage_key)
    event: dict[str, Any] = {
        'destinationReferences': [destination['reference']],
        'transactionId': f'{submission.submission_key}:{stage_key}:{integration.id}',
        'eventTimestamp': _rfc3339(timestamp),
        'lastUpdatedTimestamp': _rfc3339(submission.updated_at or timestamp),
        'consent': {
            'adUserData': 'CONSENT_GRANTED',
            'adPersonalization': 'CONSENT_GRANTED',
        },
        'eventSource': _google_event_source(submission),
        'conversionCount': 1,
    }
    if identifiers:
        event['userData'] = {'userIdentifiers': identifiers}
    if ad_identifiers:
        event['adIdentifiers'] = ad_identifiers
    if stage_key == 'won' and submission.buyer_value is not None:
        event['conversionValue'] = float(submission.buyer_value)
        event['currency'] = submission.buyer_currency or 'USD'
    if not identifiers and not ad_identifiers:
        raise GoogleDataManagerError('Google 回传缺少邮箱、电话或广告点击 ID，无法匹配。')
    return {
        'destinations': [destination],
        'events': [event],
        'validateOnly': bool(config.get('validate_only', False)),
        'encoding': 'HEX',
    }


def _load_google_credentials(integration: MarketingIntegration):
    if not settings.NEWCROWN_ALLOW_EXTERNAL_IO:
        raise GoogleDataManagerError('External I/O is disabled for this environment.')
    try:
        import google.auth
        from google.auth.transport.requests import Request
        from google.oauth2.credentials import Credentials as UserCredentials
        from google.oauth2.service_account import Credentials as ServiceAccountCredentials
    except ImportError as exc:  # pragma: no cover - deployment dependency guard
        raise GoogleDataManagerError('服务器缺少 google-auth 依赖。') from exc

    from console.secret_store import load_secret

    config = dict(integration.config_json or {})
    mode = str(config.get('credentials_mode') or 'adc').strip().lower()
    if mode == 'adc':
        credentials, _ = google.auth.default(scopes=[DATA_MANAGER_SCOPE])
    else:
        secret_ref = str(integration.secret_ref or '').strip()
        if secret_ref.startswith('vault:'):
            raw = load_secret(secret_ref.removeprefix('vault:'))
        else:
            import os

            raw = os.getenv(secret_ref, '') if secret_ref else ''
        try:
            info = json.loads(raw)
        except json.JSONDecodeError as exc:
            raise GoogleDataManagerError('Google OAuth 凭据 JSON 无法解析。') from exc
        if mode == 'authorized_user' or info.get('type') == 'authorized_user':
            credentials = UserCredentials.from_authorized_user_info(info, scopes=[DATA_MANAGER_SCOPE])
        elif mode == 'service_account' or info.get('type') == 'service_account':
            credentials = ServiceAccountCredentials.from_service_account_info(info, scopes=[DATA_MANAGER_SCOPE])
        else:
            raise GoogleDataManagerError('Google credentials_mode 必须是 adc、authorized_user 或 service_account。')
    if not credentials.valid:
        credentials.refresh(Request())
    if not credentials.token:
        raise GoogleDataManagerError('Google OAuth access token 获取失败。')
    return str(credentials.token)


def _google_request(*, method: str, url: str, token: str, payload: dict[str, Any] | None = None) -> dict[str, Any]:
    if not settings.NEWCROWN_ALLOW_EXTERNAL_IO:
        raise GoogleDataManagerError('External I/O is disabled for this environment.')
    body = json.dumps(payload).encode('utf-8') if payload is not None else None
    request = urllib.request.Request(
        url,
        data=body,
        headers={'Authorization': f'Bearer {token}', 'Content-Type': 'application/json'},
        method=method,
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            raw = response.read().decode('utf-8', errors='replace')
    except urllib.error.HTTPError as exc:
        raw = exc.read().decode('utf-8', errors='replace')
        raise GoogleDataManagerError(f'Google Data Manager HTTP {exc.code}: {raw[:800]}') from exc
    except Exception as exc:
        raise GoogleDataManagerError(f'Google Data Manager 请求失败：{str(exc)[:800]}') from exc
    try:
        parsed = json.loads(raw or '{}')
    except json.JSONDecodeError as exc:
        raise GoogleDataManagerError(f'Google Data Manager 返回非 JSON：{raw[:800]}') from exc
    if not isinstance(parsed, dict) or parsed.get('error'):
        raise GoogleDataManagerError(f'Google Data Manager 返回错误：{raw[:800]}')
    return parsed


def _save_google_failure(
    outbox: LeadEventOutbox,
    message: str,
    response: dict[str, Any] | None = None,
    *,
    increment_attempt: bool = True,
) -> bool:
    attempted_at = getattr(outbox, 'last_attempt_at', None) or timezone.now()
    outbox.status = 'failed'
    if increment_attempt:
        outbox.attempts += 1
    outbox.last_error = message[:1000]
    if response is not None:
        outbox.response_json = response
    delay_minutes = min(60, 2 ** min(max(outbox.attempts - 1, 0), 6))
    outbox.last_attempt_at = attempted_at
    outbox.next_attempt_at = attempted_at + timedelta(minutes=delay_minutes)
    outbox.updated_at = attempted_at
    outbox.save(
        update_fields=[
            'status', 'delivery_mode', 'attempts', 'last_error', 'response_json',
            'last_attempt_at', 'next_attempt_at', 'updated_at',
        ]
    )
    return False


def dispatch_google_outbox_event(outbox: LeadEventOutbox) -> bool:
    if not settings.NEWCROWN_ALLOW_EXTERNAL_IO:
        return False
    if outbox.status == 'processing':
        return refresh_google_outbox_status(outbox)
    attempted_at = timezone.now()
    outbox.delivery_mode = 'validation' if bool((outbox.payload_json or {}).get('validateOnly')) else 'live'
    outbox.last_attempt_at = attempted_at
    try:
        token = _load_google_credentials(outbox.integration)
        parsed = _google_request(
            method='POST',
            url=DATA_MANAGER_INGEST_URL,
            token=token,
            payload=outbox.payload_json,
        )
    except GoogleDataManagerError as exc:
        return _save_google_failure(outbox, str(exc))
    if bool((outbox.payload_json or {}).get('validateOnly')):
        outbox.status = 'validated'
        outbox.attempts += 1
        outbox.last_error = ''
        outbox.response_json = {**parsed, 'validationOnly': True}
        outbox.provider_received_at = attempted_at
        outbox.provider_processed_at = attempted_at
        outbox.match_status = 'not_available'
        outbox.next_attempt_at = None
        outbox.updated_at = attempted_at
        outbox.save(
            update_fields=[
                'status', 'delivery_mode', 'attempts', 'last_error', 'response_json',
                'provider_received_at', 'provider_processed_at', 'match_status',
                'last_attempt_at', 'next_attempt_at', 'updated_at',
            ]
        )
        return True

    request_id = str(parsed.get('requestId') or '').strip()
    if not request_id:
        return _save_google_failure(outbox, 'Google Data Manager 未返回 requestId。', parsed)
    outbox.status = 'processing'
    outbox.attempts += 1
    outbox.last_error = ''
    outbox.response_json = parsed
    outbox.provider_request_id = request_id
    outbox.provider_received_at = attempted_at
    outbox.next_attempt_at = attempted_at
    outbox.dispatched_at = attempted_at
    outbox.updated_at = attempted_at
    outbox.save(
        update_fields=[
            'status', 'delivery_mode', 'attempts', 'last_error', 'response_json',
            'provider_request_id', 'provider_received_at', 'last_attempt_at',
            'next_attempt_at', 'dispatched_at', 'updated_at',
        ]
    )
    return refresh_google_outbox_status(outbox, token=token)


def refresh_google_outbox_status(outbox: LeadEventOutbox, *, token: str = '') -> bool:
    if not settings.NEWCROWN_ALLOW_EXTERNAL_IO:
        return False
    attempted_at = timezone.now()
    outbox.last_attempt_at = attempted_at
    request_id = str(
        getattr(outbox, 'provider_request_id', '')
        or (outbox.response_json or {}).get('requestId')
        or ''
    ).strip()
    if not request_id:
        return _save_google_failure(
            outbox,
            'Google Data Manager requestId 缺失。',
            increment_attempt=False,
        )
    try:
        access_token = token or _load_google_credentials(outbox.integration)
        status_url = f'{DATA_MANAGER_STATUS_URL}?{urllib.parse.urlencode({"requestId": request_id})}'
        parsed = _google_request(method='GET', url=status_url, token=access_token)
    except GoogleDataManagerError as exc:
        outbox.last_error = str(exc)[:1000]
        outbox.next_attempt_at = attempted_at + timedelta(minutes=5)
        outbox.updated_at = attempted_at
        outbox.save(update_fields=['last_error', 'last_attempt_at', 'next_attempt_at', 'updated_at'])
        return False
    statuses = parsed.get('requestStatusPerDestination') or []
    status_names = {
        str(item.get('requestStatus') or '').strip().upper()
        for item in statuses
        if isinstance(item, dict) and str(item.get('requestStatus') or '').strip()
    }
    merged_response = {**(outbox.response_json or {}), 'request_status': parsed}
    outbox.response_json = merged_response
    outbox.updated_at = attempted_at
    if status_names and status_names <= {'SUCCESS'}:
        outbox.status = 'sent'
        outbox.last_error = ''
        outbox.provider_processed_at = attempted_at
        outbox.match_status = 'not_available'
        outbox.next_attempt_at = None
        outbox.dispatched_at = attempted_at
        outbox.save(
            update_fields=[
                'status', 'last_error', 'response_json', 'provider_processed_at',
                'match_status', 'last_attempt_at', 'next_attempt_at',
                'dispatched_at', 'updated_at',
            ]
        )
        return True
    if status_names & {'PROCESSING', 'REQUEST_STATUS_UNKNOWN', 'UNKNOWN'}:
        outbox.status = 'processing'
        outbox.last_error = ''
        outbox.next_attempt_at = attempted_at + timedelta(minutes=5)
        outbox.save(
            update_fields=[
                'status', 'last_error', 'response_json', 'last_attempt_at',
                'next_attempt_at', 'updated_at',
            ]
        )
        return False
    is_partial = 'PARTIAL_SUCCESS' in status_names or (
        'SUCCESS' in status_names and 'FAILED' in status_names
    )
    if is_partial:
        outbox.status = 'partial'
        error_details = google_response_errors(parsed)
        detail = f'；错误：{"；".join(error_details)}' if error_details else ''
        outbox.last_error = (
            f'Google Data Manager 部分记录成功（{", ".join(sorted(status_names))}）{detail}；'
            '为避免重复回传已停止自动重试，请人工核对失败记录。'
        )[:1000]
        outbox.provider_processed_at = attempted_at
        outbox.match_status = 'not_available'
        outbox.next_attempt_at = None
        outbox.save(
            update_fields=[
                'status', 'last_error', 'response_json', 'provider_processed_at',
                'match_status', 'last_attempt_at', 'next_attempt_at', 'updated_at',
            ]
        )
        return False
    if status_names and status_names <= {'FAILED'}:
        outbox.status = 'failed'
        error_details = google_response_errors(parsed)
        detail = f'；错误：{"；".join(error_details)}' if error_details else ''
        outbox.last_error = (
            f'Google Data Manager 处理失败（{", ".join(sorted(status_names))}）{detail}'
        )[:1000]
        delay_minutes = min(60, 2 ** min(max(outbox.attempts - 1, 0), 6))
        outbox.provider_processed_at = attempted_at
        outbox.match_status = 'not_available'
        outbox.next_attempt_at = attempted_at + timedelta(minutes=delay_minutes)
        outbox.save(
            update_fields=[
                'status', 'last_error', 'response_json', 'provider_processed_at',
                'match_status', 'last_attempt_at', 'next_attempt_at', 'updated_at',
            ]
        )
        return False
    outbox.status = 'processing'
    outbox.last_error = ''
    outbox.next_attempt_at = attempted_at + timedelta(minutes=5)
    outbox.save(
        update_fields=[
            'status', 'last_error', 'response_json', 'last_attempt_at',
            'next_attempt_at', 'updated_at',
        ]
    )
    return False
