from django.urls import path
from . import views
from . import marketing_views
from . import sales_views
from . import lead_views_v2
from . import opportunity_views_v2
from . import account_views_v2
from . import marketing_event_views
from . import task_views_v2
from . import workbench_views
from . import whatsapp_views_v2
from . import customer_pool_views
from . import customer_pool_exports

app_name = 'console'

urlpatterns = [
    path('', views.home, name='home'),
    path('workbench/', workbench_views.workbench, name='workbench'),
    path('marketing/events/', marketing_event_views.marketing_events, name='marketing_events'),
    path('marketing/forms/', views.marketing_forms, name='marketing_forms'),
    path('marketing/forms/new/', views.lead_form_create, name='marketing_form_create'),
    path('marketing/forms/<int:form_id>/', views.lead_form_edit, name='marketing_form_edit'),
    path('sales/opportunities/', opportunity_views_v2.opportunity_workspace_v2, name='opportunity_workspace_v2'),
    path('sales/opportunities/<int:opportunity_id>/', opportunity_views_v2.opportunity_workspace_detail_v2, name='opportunity_workspace_detail_v2'),
    path('sales/companies/', account_views_v2.company_workspace_v2, name='company_workspace_v2'),
    path('sales/customer-pool/', customer_pool_views.customer_pool, name='customer_pool'),
    path('sales/customer-pool/template.xlsx', customer_pool_views.customer_pool_template, name='customer_pool_template'),
    path('sales/customer-pool/import/', customer_pool_views.customer_pool_import, name='customer_pool_import'),
    path('sales/customer-pool/export/', customer_pool_exports.customer_pool_export, name='customer_pool_export'),
    path('sales/customer-pool/export/standard21/', customer_pool_exports.customer_pool_export_standard21, name='customer_pool_export_standard21'),
    path('sales/customer-pool/export/status/', customer_pool_exports.customer_pool_export_status, name='customer_pool_export_status'),
    path('sales/customer-pool/export/<int:job_id>/download/', customer_pool_exports.customer_pool_export_download, name='customer_pool_export_download'),
    path('sales/customer-pool/export/<int:job_id>/retry/', customer_pool_exports.customer_pool_export_retry, name='customer_pool_export_retry'),
    path('sales/customer-pool/export/<int:job_id>/cancel/', customer_pool_exports.customer_pool_export_cancel, name='customer_pool_export_cancel'),
    path('sales/customer-pool/search-contact/', customer_pool_views.customer_pool_contact_search, name='customer_pool_contact_search'),
    path('sales/customer-pool/new/', customer_pool_views.customer_pool_manual_create, name='customer_pool_manual_create'),
    path('sales/customer-pool/<int:company_id>/', customer_pool_views.customer_pool_detail, name='customer_pool_detail'),
    path('sales/customer-pool/<int:company_id>/claim/', customer_pool_views.customer_pool_claim, name='customer_pool_claim'),
    path('sales/customer-pool/bulk-claim/', customer_pool_views.customer_pool_bulk_claim, name='customer_pool_bulk_claim'),
    path('sales/customer-pool/<int:company_id>/assign/', customer_pool_views.customer_pool_assign, name='customer_pool_assign'),
    path('sales/customer-pool/<int:company_id>/review/', customer_pool_views.customer_pool_review, name='customer_pool_review'),
    path('sales/customer-pool/<int:company_id>/archive/', customer_pool_views.customer_pool_archive, name='customer_pool_archive'),
    path('sales/customer-pool/<int:company_id>/restore/', customer_pool_views.customer_pool_restore, name='customer_pool_restore'),
    path('sales/customer-pool/<int:company_id>/release/', customer_pool_views.customer_pool_release, name='customer_pool_release'),
    path('sales/companies/<int:company_id>/', account_views_v2.company_workspace_detail_v2, name='company_workspace_detail_v2'),
    path('sales/contacts/', account_views_v2.contact_workspace_v2, name='contact_workspace_v2'),
    path('sales/contacts/<int:contact_id>/', account_views_v2.contact_workspace_detail_v2, name='contact_workspace_detail_v2'),
    path('sales/tasks/', task_views_v2.task_workspace_v2, name='task_workspace_v2'),
    path('sales/tasks/new/', task_views_v2.task_new_v2, name='task_new_v2'),
    path('sales/tasks/<int:task_id>/', task_views_v2.task_workspace_detail_v2, name='task_workspace_detail_v2'),
    path('sales/activities/<int:activity_id>/', task_views_v2.activity_workspace_detail_v2, name='activity_workspace_detail_v2'),
    path('api/sales/targets/search/', task_views_v2.task_target_search_v2, name='task_target_search_v2'),
    path('api/sales/contacts/<int:contact_id>/company-options/', account_views_v2.contact_company_options_v2, name='contact_company_options_v2'),
    path('sales/leads/', lead_views_v2.lead_workspace_v2, name='lead_workspace_v2'),
    path('sales/leads/<int:submission_id>/', lead_views_v2.lead_workspace_detail_v2, name='lead_workspace_detail_v2'),
    path('api/sales/leads/<int:submission_id>/disposition/', lead_views_v2.lead_disposition_v2, name='lead_disposition_v2'),
    path('api/sales/leads/bulk-assign/', lead_views_v2.lead_bulk_assign_v2, name='lead_bulk_assign_v2'),
    path('sales/whatsapp/', whatsapp_views_v2.whatsapp_workspace_v2, name='whatsapp_workspace_v2'),
    path('sales/whatsapp/<int:conversation_id>/', whatsapp_views_v2.whatsapp_workspace_detail_v2, name='whatsapp_workspace_detail_v2'),
    path('api/sales/whatsapp/<int:conversation_id>/send/', whatsapp_views_v2.whatsapp_send_v2, name='whatsapp_send_v2'),
    path('api/sales/whatsapp/<int:conversation_id>/note/', whatsapp_views_v2.whatsapp_note_v2, name='whatsapp_note_v2'),
    path('api/sales/whatsapp/<int:conversation_id>/assign/', whatsapp_views_v2.whatsapp_assign_v2, name='whatsapp_assign_v2'),
    path('api/sales/whatsapp/<int:conversation_id>/state/', whatsapp_views_v2.whatsapp_state_v2, name='whatsapp_state_v2'),
    path('api/sales/whatsapp/<int:conversation_id>/read/', whatsapp_views_v2.whatsapp_mark_read_v2, name='whatsapp_mark_read_v2'),
    path('api/sales/whatsapp/<int:conversation_id>/messages/<int:message_id>/retry/', whatsapp_views_v2.whatsapp_retry_v2, name='whatsapp_retry_v2'),
    path('api/sales/whatsapp/<int:conversation_id>/messages/<int:message_id>/media/<int:media_id>/', whatsapp_views_v2.whatsapp_media_download_v2, name='whatsapp_media_download_v2'),
    path('sales/', views.sales_workspace, name='sales_workspace'),
    path('api/workbench/', sales_views.workbench_data, name='workbench_data'),
    path('api/sales/pipeline/', sales_views.pipeline_data, name='pipeline_data'),
    path('api/sales/records/<str:target_type>/<int:target_id>/', sales_views.crm_record_detail, name='crm_record_detail'),
    path('api/sales/companies/<int:company_id>/update/', sales_views.company_update, name='company_update'),
    path('api/sales/contacts/<int:contact_id>/update/', sales_views.contact_update, name='contact_update'),
    path('api/sales/opportunities/<int:opportunity_id>/update/', sales_views.opportunity_update, name='opportunity_update'),
    path('api/sales/attachments/', sales_views.crm_attachments, name='crm_attachments'),
    path('api/sales/attachments/<int:attachment_id>/download/', sales_views.crm_attachment_download, name='crm_attachment_download'),
    path('api/sales/attachments/<int:attachment_id>/archive/', sales_views.crm_attachment_archive, name='crm_attachment_archive'),
    path('api/sales/leads/<int:submission_id>/convert/', sales_views.lead_convert, name='lead_convert'),
    path('api/sales/activities/', task_views_v2.activity_create_v2, name='activity_create'),
    path('api/sales/activities/<int:activity_id>/corrections/', task_views_v2.activity_correction_v2, name='activity_correction_v2'),
    path('api/sales/tasks/', task_views_v2.task_create_v2, name='task_create'),
    path('api/sales/opportunities/create/', task_views_v2.opportunity_create_v2, name='opportunity_create_v2'),
    path('api/sales/tasks/<int:task_id>/update/', task_views_v2.task_update_v2, name='task_update_v2'),
    path('api/sales/tasks/<int:task_id>/start/', task_views_v2.task_start_v2, name='task_start_v2'),
    path('api/sales/tasks/<int:task_id>/complete/', task_views_v2.task_complete_v2, name='task_complete'),
    path('api/sales/tasks/<int:task_id>/cancel/', task_views_v2.task_cancel_v2, name='task_cancel_v2'),
    path('api/sales/tasks/bulk-assign/', task_views_v2.task_bulk_assign_v2, name='task_bulk_assign_v2'),
    path('api/sales/opportunities/<int:opportunity_id>/stage/', sales_views.opportunity_stage, name='opportunity_stage'),
    path('api/sales/saved-views/', sales_views.saved_view_save, name='saved_view_save'),
    path('api/sales/bulk-assign/', sales_views.bulk_assign, name='sales_bulk_assign'),
    path('api/sales/collections/<str:collection>/', sales_views.crm_collection_data, name='crm_collection_data'),
    path('api/marketing/overview/', marketing_views.marketing_overview_data, name='marketing_overview_data'),
    path('api/marketing/integrations/<int:integration_id>/evidence/', marketing_views.integration_evidence_data, name='integration_evidence_data'),
    path('api/marketing/integrations/<int:integration_id>/diagnose/', marketing_views.integration_diagnose, name='integration_diagnose'),
    path('api/marketing/outbox/<int:outbox_id>/retry/', marketing_views.marketing_outbox_retry, name='marketing_outbox_retry'),
    path('api/marketing/inbound/<int:receipt_id>/retry/', marketing_event_views.marketing_inbound_retry, name='marketing_inbound_retry'),
    path('api/privacy/requests/', marketing_views.privacy_requests_data, name='privacy_requests_data'),
    path('api/privacy/requests/create/', marketing_views.privacy_request_create, name='privacy_request_create'),
    path('api/privacy/requests/<int:privacy_request_id>/update/', marketing_views.privacy_request_update, name='privacy_request_update'),
    path('api/privacy/requests/<int:privacy_request_id>/export/', marketing_views.privacy_request_export, name='privacy_request_export'),
    path('api/privacy/requests/<int:privacy_request_id>/execute/', marketing_views.privacy_request_execute, name='privacy_request_execute'),
    path('api/system/privacy-retention/', marketing_views.retention_policy_data, name='retention_policy_data'),
    path('api/system/privacy-retention/update/', marketing_views.retention_policy_update, name='retention_policy_update'),
    path('api/system/privacy-retention/execute/', marketing_views.retention_policy_execute, name='retention_policy_execute'),
    path('content/articles/', views.content_articles, name='content_articles'),
    path('articles/', views.articles, name='articles'),
    path('articles/import/', views.article_import, name='article_import'),
    path('articles/export/', views.article_export, name='article_export'),
    path('articles/locales/new/', views.article_locale_create, name='article_locale_create'),
    path('articles/locales/<int:locale_id>/enable/', views.article_locale_enable, name='article_locale_enable'),
    path('articles/locales/<int:locale_id>/disable/', views.article_locale_disable, name='article_locale_disable'),
    path('articles/locales/<int:locale_id>/make-default/', views.article_locale_make_default, name='article_locale_make_default'),
    path('articles/categories/', views.article_categories, name='article_categories'),
    path('articles/categories/new/', views.category_create, name='category_create'),
    path('articles/categories/<int:category_id>/', views.category_edit, name='category_edit'),
    path('articles/new/', views.article_create, name='article_create'),
    path('articles/<int:article_id>/', views.article_edit, name='article_edit'),
    path('assets/', views.assets, name='assets'),
    path('assets/3d/', views.assets_three_d, name='assets_three_d'),
    path('assets/3d/assets/<int:asset_id>/', views.three_d_asset_detail, name='three_d_asset_detail'),
    path('assets/3d/profiles/new/', views.three_d_profile_create, name='three_d_profile_create'),
    path('assets/3d/profiles/<int:profile_id>/', views.three_d_profile_edit, name='three_d_profile_edit'),
    path('assets/3d/placements/new/', views.three_d_placement_create, name='three_d_placement_create'),
    path('assets/3d/placements/<int:placement_id>/', views.three_d_placement_edit, name='three_d_placement_edit'),
    path('assets/upload/', views.asset_upload, name='asset_upload'),
    path('assets/import-local/', views.asset_import_path, name='asset_import_path'),
    path('assets/<int:asset_id>/file/', views.asset_file, name='asset_file'),
    path('marketing/attribution/', views.marketing_attribution, name='marketing_attribution'),
    path('marketing/', views.marketing, name='marketing'),
    path('marketing/integrations/<int:integration_id>/', views.marketing_integration_edit, name='marketing_integration_edit'),
    path('marketing/privacy/', views.marketing_privacy, name='marketing_privacy'),
    path('marketing/privacy/new/', views.privacy_request_register, name='privacy_request_register'),
    path('marketing/privacy/<int:privacy_request_id>/', views.privacy_request_manage, name='privacy_request_manage'),
    path('leads/', views.leads, name='leads'),
    path('leads/email-settings/', views.smtp_settings, name='smtp_settings'),
    path('leads/forms/new/', views.lead_form_create, name='lead_form_create'),
    path('leads/forms/<int:form_id>/', views.lead_form_edit, name='lead_form_edit'),
    path('leads/submissions/export.csv', views.lead_submission_export_csv, name='lead_submission_export_csv'),
    path('leads/submissions/export.xlsx', views.lead_submission_export_xlsx, name='lead_submission_export_xlsx'),
    path('leads/submissions/<int:submission_id>/', views.lead_submission_edit, name='lead_submission_edit'),
    path('leads/submissions/bulk-stage/', views.lead_submission_bulk_stage, name='lead_submission_bulk_stage'),
    path('leads/outbox/<int:outbox_id>/dispatch/', views.lead_outbox_dispatch, name='lead_outbox_dispatch'),
    path('leads/outbox/dispatch-pending/', views.lead_outbox_dispatch_pending, name='lead_outbox_dispatch_pending'),
    path('system/users/', views.system_users, name='system_users'),
    path('system/users/new/', views.system_user_create, name='system_user_create'),
    path('system/users/<int:user_id>/', views.system_user_edit, name='system_user_edit'),
    path('system/teams/', views.system_teams, name='system_teams'),
    path('system/teams/new/', views.system_team_create, name='system_team_create'),
    path('system/teams/<int:team_id>/', views.system_team_edit, name='system_team_edit'),
    path('system/email/', views.smtp_settings, name='system_email'),
    path('system/data-governance/', views.system_data_governance, name='system_data_governance'),
    path('api/leads/forms/<str:form_code>/definition/', views.public_lead_form_definition, name='public_lead_form_definition'),
    path('releases/', views.releases, name='releases'),
    path('releases/build-preview/', views.release_build_preview, name='release_build_preview'),
    path('api/leads/forms/<str:form_code>/submit/', views.public_lead_submit, name='public_lead_submit'),
]
